version: '3.3'
services:
  # copied from https://github.com/calvinlfer/compose-cassandra-cluster/blob/master/docker-compose.yml
  cassandra-seed-id-service:
    container_name: cassandra-seed-id-service
    image: cassandra:4.0.7
    ports:
      - 9042:9042   # Native transport
      - 9160:9160   # Thrift clients
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    logging:
      driver: none

  cassandra-node-1-id-service:
    container_name: cassandra-node-1-id-service
    image: cassandra:4.0.7
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-seed-id-service
    depends_on:
      - cassandra-seed-id-service
    logging:
      driver: none

  acct_postgres:
    image: postgres:13.2
    restart: always
    container_name: acct_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  acct_kafka:
    image: obsidiandynamics/kafka
    container_name: acct_kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://acct_kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_SESSION_TIMEOUT=6000
      - KAFKA_RESTART_ATTEMPTS=10
      - KAFKA_RESTART_DELAY=5
      - ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL=0

  acct_kafdrop:
    image: 'obsidiandynamics/kafdrop'
    container_name: acct_kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=acct_kafka:29092
      - JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
    depends_on:
      - acct_kafka
